### ISSUE TITLE
 was built for newer iOS version (10.2) than being linked (8.0) duplicate symbol _OBJC_CLASS_$_TableHeaderView in

### ISSUE THREAD

**Issue by MansionWayh** [jinht/Marquee#1]
was built for newer iOS version (10.2) than being linked (8.0)
duplicate symbol _OBJC_CLASS_$_TableHeaderView in

导入项目的时候，不能用，

**Comment by jinht** [comment]
@MansionWayh 感谢反馈，现已纠正
