### ISSUE TITLE
作者您这个前后台进入，我认为你得判断之前是什么的状态吧，这个库里面是不管之前是暂停还是播放的，进入前后一律播放

### ISSUE THREAD

**Issue by misaka14** [jinht/Marquee#10]

**Comment by jinht** [comment]
@misaka14 你说的很是时候，我昨天已经在考虑这个问题了，可以的话，今天我会做更新

**Comment by misaka14** [comment]
是不是少了arm64的架构？

**Comment by jinht** [comment]
@misaka14 没少

**Comment by jinht** [comment]
@misaka14 
Xcode9.0
![add sdk](https://user-images.githubusercontent.com/13724367/30894372-030af0c2-a376-11e7-87e5-6b8cd37e08de.png)

**Comment by misaka14** [comment]
已解决，3Q

发自网易邮箱大师
在2017年09月27日 11:21，JZ<mailto:notifications@github.com> 写道：

@misaka14<https://github.com/misaka14>
Xcode9.0
[add sdk]<https://user-images.githubusercontent.com/13724367/30894372-030af0c2-a376-11e7-87e5-6b8cd37e08de.png>
