### ISSUE TITLE
代码无法运行，请更新下谢谢 或者是可能我设置错啦？

### ISSUE THREAD

**Issue by zhouhaokefd** [jinht/Marquee#13]

**Comment by zhouhaokefd** [comment]
Ld /Users/apple/Library/Developer/Xcode/DerivedData/JhtMarquee-cfjwxxjbtkkxuravmleqidixfdlg/Build/Intermediates/JhtMarquee.build/Debug-iphonesimulator/JhtMarquee.build/Objects-normal/x86_64/JhtMarquee normal x86_64
    cd /Users/apple/Downloads/Marquee-master-2
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -L/Users/apple/Library/Developer/Xcode/DerivedData/JhtMarquee-cfjwxxjbtkkxuravmleqidixfdlg/Build/Products/Debug-iphonesimulator -F/Users/apple/Library/Developer/Xcode/DerivedData/JhtMarquee-cfjwxxjbtkkxuravmleqidixfdlg/Build/Products/Debug-iphonesimulator -F/Users/apple/Downloads/Marquee-master-2/JhtMarquee.framework -F/Users/apple/Downloads/Marquee-master-2 -filelist /Users/apple/Library/Developer/Xcode/DerivedData/JhtMarquee-cfjwxxjbtkkxuravmleqidixfdlg/Build/Intermediates/JhtMarquee.build/Debug-iphonesimulator/JhtMarquee.build/Objects-normal/x86_64/JhtMarquee.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/JhtMarquee-cfjwxxjbtkkxuravmleqidixfdlg/Build/Intermediates/JhtMarquee.build/Debug-iphonesimulator/JhtMarquee.build/Objects-normal/x86_64/JhtMarquee_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/JhtMarquee-cfjwxxjbtkkxuravmleqidixfdlg/Build/Intermediates/JhtMarquee.build/Debug-iphonesimulator/JhtMarquee.build/JhtMarquee.app.xcent -framework JhtMarquee -Xlinker -dependency_info -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/JhtMarquee-cfjwxxjbtkkxuravmleqidixfdlg/Build/Intermediates/JhtMarquee.build/Debug-iphonesimulator/JhtMarquee.build/Objects-normal/x86_64/JhtMarquee_dependency_info.dat -o /Users/apple/Library/Developer/Xcode/DerivedData/JhtMarquee-cfjwxxjbtkkxuravmleqidixfdlg/Build/Intermediates/JhtMarquee.build/Debug-iphonesimulator/JhtMarquee.build/Objects-normal/x86_64/JhtMarquee

ld: framework not found FileProvider for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zhouhaokefd** [comment]
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'JhtMarquee/Info.plist'.

**Comment by jinht** [comment]
@zhouhaokefd 你参考一下demo的使用配置

**Comment by zhouhaokefd** [comment]
在哪里可以查看到。。。。有链接吗

**Comment by zhouhaokefd** [comment]
现在demo无法运行 一运行就报上面的错误

**Comment by jinht** [comment]
@zhouhaokefd 用最新的Xcode打开试试

**Comment by zhouhaokefd** [comment]
今天尝试啦下更新Xcode 和重新下代码  还是昨天的那个情况，无法运行。。0.0

**Comment by jinht** [comment]
@zhouhaokefd 重新下载试试

**Comment by zhouhaokefd** [comment]
可以运行啦谢谢

**Comment by jinht** [comment]
@zhouhaokefd 问题的主要缘由就是Xcode version 无法向上兼容，欢迎star使用，后续有问题可以随时沟通
