### ISSUE TITLE
您好，verticalTextAlignment的问题

### ISSUE THREAD

**Issue by chenwh** [jinht/Marquee#15]
当设置verticalTextAlignment 为NSTextAlignmentLeft的时候，文字会挨着边，不是很美观，我猜测，您这个可能是UITextField，可否开放粗来leftView，这样我们可以定制 文字距离 边的大小，

**Comment by chenwh** [comment]
额，有个投机的方法，在要显示的字符前加空格

**Comment by jinht** [comment]
@chenwh 忙过这几天我会做相应更新

**Comment by jinht** [comment]
@chenwh 我想了一下，marquee和UITextField还是有区别的，假使有leftView这样的需求可以将marquee作为一个独立小控件来使用，这样貌似灵活些
