### ISSUE TITLE
你好，我用Masonry布局怎么就跑不起来？

### ISSUE THREAD

**Issue by 542604974** [jinht/Marquee#16]
JhtHorizontalMarquee * amountLabel = [[JhtHorizontalMarquee alloc] initWithFrame:CGRectZero withSingleScrollDuration:8.0];
        [amountLabel marqueeOfSettingWithState:MarqueeStart_H];
        [self.contentView addSubview:amountLabel];
  [amountLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.mas_equalTo(-kSpacingDistance);
            make.centerY.mas_equalTo(self.contentView.mas_centerY);
            make.height.mas_equalTo(20);
            make.left.mas_equalTo(typeLabel.mas_right).offset(5);
        }];

**Comment by 542604974** [comment]
就是横向滚动

**Comment by jinht** [comment]
@542604974 没有你这样尝试过，你可以尝试一下别的方式
