### ISSUE TITLE
JhtMarquee/JhtVerticalMarquee.h' file not found

### ISSUE THREAD

**Issue by MansionWayh** [jinht/Marquee#17]
导入项目里的时候，编译的时候，提示找不到文件名。
![2017-12-13 5 42 22](https://user-images.githubusercontent.com/16216828/33932184-390bf04c-e02d-11e7-925f-78768924f1c7.png)

**Comment by jinht** [comment]
@MansionWayh 
看看这个路径添加的是否正确
<img width="868" alt="2017-12-13 17 46 24" src="https://user-images.githubusercontent.com/13724367/33932569-38659df4-e02e-11e7-81e1-37c3559bc076.png">

**Comment by MansionWayh** [comment]
为什么一进入程序的时候，marquee是不走的。只有在viewwillappear的时候，marquee才动起来。怎么设置他一进入程序就直接启动了。

**Comment by jinht** [comment]
@MansionWayh 初始化 && 传入数据后，均可以通过相应Public Method 进行控制
