### ISSUE TITLE
经常会报这些unrecognized selector的错误，而且是在iOS8上，退出应用程序的时候

### ISSUE THREAD

**Issue by LuPing-Kuang** [jinht/Marquee#19]
[__NSCFType hmqShutdownMarquee]: unrecognized selector sent to instance 0x14de0fde0
PiaoGen + 679488

**Comment by jinht** [comment]
@LuPing-Kuang 这个早就知晓，有遇到crash状况没？

**Comment by jinht** [comment]
@LuPing-Kuang 是最新SDK吗？

**Comment by LuPing-Kuang** [comment]
是最新的，你可以看看在iOS8运行的效果，当控制器进入后台的时候就崩溃了

**Comment by jinht** [comment]
@LuPing-Kuang 你使用demo也会崩溃吗？

**Comment by jinht** [comment]
@LuPing-Kuang 你用的是iOS系统哪个版本？我使用8.1未出现此问题

**Comment by kthree0830** [comment]
是崩溃啊,8.3,请问如何处理
