### ISSUE TITLE
有一下问题

### ISSUE THREAD

**Issue by DongfengWang123** [jinht/Marquee#21]
已经知道了，但是有两个问题，1.你的这样无法设置字体的颜色和大小吧，我想要使用NSAttributedString的模式进行显示，可是实现不了；2.如果内容特别特别多的时候，跑马灯就不会跑了

**Comment by jinht** [comment]
@DongfengWang123 
1. 使用NSAttributedString 为什么不能设置呢？
2. 多到多少的时候《跑马灯就不会跑了》呢？

**Comment by hellokrystal** [comment]
不能设置 你这个设置不了 鸡肋啊

**Comment by jinht** [comment]
你可以自己写一个或者换一个
