### ISSUE TITLE
为啥设置时间呢 能不能改成自己设置速度的

### ISSUE THREAD

**Issue by Qinzhao** [jinht/Marquee#24]
为啥设置时间呢 能不能改成自己设置速度的

**Comment by jinht** [comment]
@Qinzhao 滚动速度根据时间设定来调整的，暂时不能支持你所描述的方式

**Comment by Qinzhao** [comment]
好吧，因为后台文字可能特别长  导致滚动特别快  那我根据文字自行算下时间  谢谢~
