### ISSUE TITLE
开放源代码问题

### ISSUE THREAD

**Issue by CoderJJMa** [jinht/Marquee#3]
你好,今天下载了这个demo,效果不错哈,先给个✨在看!!!  如果代码开源了,会学到更多,望考虑哈~~

**Comment by jinht** [comment]
@JJCoderiOS 还在优化中，假使开源，我希望尽量能够给予他人正确的引导，还在努力中，使用上遇到什么问题可以随时交流

**Comment by FrankCYQ** [comment]
亲，你这个能支持富媒体文字么，比如在针对特殊文字加背景色？

**Comment by jinht** [comment]
@FrankCYQ 目前还不支持，最近有点小忙，之后会支持的

**Comment by sesameImmortals** [comment]
看不了源码...

**Comment by Maguangran** [comment]
求开源
