### ISSUE TITLE
[!] Unable to find a specification for `JhtMarquee`

### ISSUE THREAD

**Issue by aStudyer** [jinht/Marquee#33]

**Comment by jinht** [comment]
首先 感谢反馈，但我没有 复现 你的问题，能详细描述一下吗？

**Comment by aStudyer** [comment]
就是cocoapods执行install的时候提示这个，找不到你这个仓库，pod search也找不到，另外，可以给一份源码吗？我可能需要修改一些地方，符合我们的需求？

**Comment by jinht** [comment]
![5e389099-9746-4d11-8cd2-35a42f1efdc0](https://user-images.githubusercontent.com/13724367/50414103-7b437300-084e-11e9-9ae8-e2b015f6bc74.png)

**Comment by aStudyer** [comment]
朋友能否给一个联系方式？我有些问题需要请教
