### ISSUE TITLE
pod搜索不到

### ISSUE THREAD

**Issue by Vutumn** [jinht/Marquee#35]

**Comment by Vutumn** [comment]
并没有找到这个pod的安装方式，提供的jhtMarquee，提示找不到。

**Comment by lailibo8** [comment]
是的，根本都找不到

**Comment by jinht** [comment]
<img width="1229" alt="2019-03-04 10 36 31" src="https://user-images.githubusercontent.com/13724367/53707399-cb037380-3e69-11e9-93b3-a89ea02f0c0e.png">
![8158520a60f5f524f4cc73aa5c7eda6a](https://user-images.githubusercontent.com/13724367/53707403-cccd3700-3e69-11e9-8cd3-3e00376a06f9.jpg)
<img width="929" alt="2019-03-04 10 39 15" src="https://user-images.githubusercontent.com/13724367/53707406-d060be00-3e69-11e9-8fd8-16d6b7fb7972.png">
@Vutumn @lailibo8
