### ISSUE TITLE
不适配ios7

### ISSUE THREAD

**Issue by PengJiang520** [jinht/Marquee#4]
Object file (/Users/PengJiang/Desktop/项目/天宝/app/app/JhtMarqueeSDK/JhtMarqueeSDK.a(JhtHorizontalMarquee.o)) was built for newer iOS version (8.0) than being linked (7.0)

**Comment by jinht** [comment]
是的，readme里面又说名有说明
<img width="305" alt="2017-05-09 4 28 05" src="https://cloud.githubusercontent.com/assets/13724367/25841914/980fbe5c-34d4-11e7-82cd-e170e172b52b.png">

**Comment by PengJiang520** [comment]
能否开源 大神 我这边也好改
