### ISSUE TITLE
可以支持NSAttributedString文字么？

### ISSUE THREAD

**Issue by FrankCYQ** [jinht/Marquee#7]
亲，你这个能支持富媒体文字么，比如在针对特殊文字加背景色？目前静态库看不了实现方式

**Comment by jinht** [comment]
@FrankCYQ JhtHorizontalMarquee支持attributedText

**Comment by FrankCYQ** [comment]
感谢您的回答，目前需求是需要垂直方向滚动。

**Comment by jinht** [comment]
@FrankCYQ 晚上我看看吧

**Comment by jinht** [comment]
@FrankCYQ 都支持啦

**Comment by FrankCYQ** [comment]
其实这个很简单，就是可以将传入的string 扩展为NSAttributeString就ok了
